#!/bin/bash

# GIT status flag
function __git_status_flag {
    git_status="$(git status 2> /dev/null)"
    remote_pattern="# Your branch is \(. of"
    diverge_pattern="# Your branch and \(. have diverged"
    if [[ ! ${git_status}} =~ "working directory clean" ]]; then
        state="⚡"
        spacer=" "
    fi

    if [[ ${git_status} =~ ${remote_pattern} ]]; then
        spacer=" "
        if [[ ${BASH_REMATCH[1]} == "ahead" ]]; then
            remote="↑"
        else
            remote="↓"
        fi
    fi

    if [[ ${git_status} =~ ${diverge_pattern} ]]; then
        remote="↕"
        spacer=" "
    fi

    echo "${state}${remote}${spacer}"
}

source ~/.bash-addons/.git-prompt.sh;
export PS1='\[\e[1;34m\]\W\[\e[22;35m\]$(__git_ps1 " [\[\e[33m\]$(__git_status_flag)\[\e[35m\]%s]")\[\e[33m\] \$ \[\e[0m\]';
