#!/bin/bash

alias showHiddenFiles="defaults write com.apple.finder AppleShowAllFiles YES"
alias hideHiddenFiles="defaults write com.apple.finder AppleShowAllFiles NO"

up() {
  dirs=${1:-1}
  while [ ${dirs} -gt 0 ]; do
      cd ..
      dirs=$((dirs-1))
  done
}

alias path='echo -e ${PATH//:/\\n}'
alias clearDNS='sudo discoveryutil mdnsflushcache'
function removeFromLaunchPad() { sqlite3 $(sudo find /private/var/folders -name com.apple.dock.launchpad)/db/db "DELETE FROM apps WHERE title='$1';"; killall Dock; }


grepj() {
    grep -r "$1" . --include \*.java
}

grepx() {
    grep -r "$1" . --include \*.xml
}

grepjx() {
    grep -r "$1" . --include \*.java --include \*.xml
}
